jobs: 
  build: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps: 
       - checkout
       - run: dotnet build     
       
  test: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1    
    steps: 
      - checkout
      - run: echo "test"
       
workflows: 
  version: 2
  build_and_test: 
    jobs: 
      - build
      - test
