#Remember and use cache, env variables and persist_to_workspace/attach_workspace
jobs: 
  build: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps: 
      - checkout    
      - run: dotnet build
      - run: ls
      - run: cd /root/project/bhamTAF
      - run: Vstest.console.exe bhamTAF.dll 
       
  test: 
    #docker:
    #  - image: mcr.microsoft.com/dotnet/core/sdk:3.1    
    steps: 
      - run: ls
      - run: cd /root/project/bhamTAF/bin/Debug/netcoreapp3.1
      - run: cd C:\\Dev\\bhamTAF\\bhamTAF\\bin\\Debug\\netcoreapp3.1
      - run: Vstest.console.exe bhamTAF.dll      
       
workflows: 
  version: 2
  build_and_test: 
    jobs: 
      - build
      - test:        
          requires:
            - build
