 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   jobOne:
     executor: win/default
     steps:
       - checkout
       - run: dotnet build       
   jobTwo:
     executor: win/default 
     steps:
       - checkout
       - run: echo "test"
 
