jobs: 
  build: 
    executor: win/default
    steps: 
       - checkout
       - run: dotnet build     
       
  test: 
    executor: win/default 
     
    steps: 
      - checkout
      - run: echo "test"
       
workflows: 
  version: 2
  build_and_test: 
    jobs: 
      - build
      - test
