jobs: 
  build: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps: 
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run: dotnet build     
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
       
  test: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1    
    steps: 
      - checkout
      - attach_workspace:
        at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It Worked";
          else
            echo "NO!"; exit 1
          fi            
       
workflows: 
  version: 2
  build_and_test: 
    jobs: 
      - build
      - test:        
          requires:
            - build
