#Remember and use cache, env variables and persist_to_workspace/attach_workspace
jobs: 
  build: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps: 
      - checkout
      - run: mkdir -p my_workspace      
      - run: dotnet build
      - run: cd C:\\Dev\\bhamTAF\\bhamTAF\\
       
  test: 
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1    
    steps: 
      - run: echo ls
      - run: echo dir
      - run: cd C:\\Dev\\bhamTAF\\bhamTAF\\bin\\Debug\\netcoreapp3.1
      - run: Vstest.console.exe bhamTAF.dll      
       
workflows: 
  version: 2
  build_and_test: 
    jobs: 
      - build
      - test:        
          requires:
            - build
